name: Java Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Resolve .jar name
      id: prep
      run: |
        JAR_PATH=`echo **/DeathSwap-*[^shaded].jar`
        JAR_NAME=`basename ${JAR_PATH}`

        echo ::set-output name=jar_path::${JAR_PATH}
        echo ::set-output name=jar_name::${JAR_NAME}
    - name: Upload .jar
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.prep.outputs.jar_name }}
        path: ${{ steps.prep.outputs.jar_path }}
